### ISSUE TITLE
Add multi-arch support

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/docker-images#195]
Add the following to the GitHub worklfow to support multiple architectures:
```yaml
- name: Set up QEMU
  uses: docker/setup-qemu-action@v2
```

Resources:
* [Building Multi-Arch Docker Images via Github Actions](https://blog.thesparktree.com/docker-multi-arch-github-actions)

**Comment by adamhgriffith-uofu** [comment]
Re-opening. Missing a few steps. For example:
```yaml
- name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Release image
        uses: docker/build-push-action@v4
        with:
          ...
          platforms: linux/amd64,linux/arm64
```
