### ISSUE TITLE
Write slate-api-worker image

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/docker-images#23]
The [slateci/helm-slate-api](https://github.com/slateci/helm-slate-api) will require a worker image with dependencies allowing the scripts defined at [slateci/slate-server-scripts](https://github.com/slateci/slate-server-scripts).

**Comment by adamhgriffith-uofu** [comment]
Example usage in Helm might resemble:
```yml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-collect-map-data
  namespace: {{ .Values.namespace }}
  labels:
    tier: {{ .Values.tierLabels.api}}
    stage: {{ .Values.stage }}
spec:
  schedule: "{{ .Values.cronjobs.collect-map-data }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: runner
              image: "<make a worker image>"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - cd /slate/scripts
                - chmod +x ./collect_map_data.sh
                - /collect_map_data.sh
              env:
                - name: SLATE_API_ENDPOINT
                  value: {{ XXXX }}
                - name: SLATE_API_PORT
                  value: {{ .Values.apiPort }}
                - name: SLATE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-api-token
                      key: api_token
                - name: SLATE_awsAccessKey
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-aws-secret
                      key: aws_access_key
                - name: SLATE_awsSecretKey
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-aws-secret
                      key: aws_secret_key
              volumeMounts:
                - name: slate-conf
                  mountPath: /slate
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: slate-conf
              configMap:
                name: {{ .Release.Name }}-slate-conf-configmap
```
